"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const risk_manager_controller_1 = require("../controllers/risk-manager.controller");
const router = (0, express_1.Router)();
const controller = new risk_manager_controller_1.RiskManagerController();
router.post('/', controller.create);
router.get('/', controller.getAll);
router.get('/:id', controller.getById);
router.put('/:id', controller.update);
router.delete('/:id', controller.delete);
exports.default = router;
